os:
  - linux

language: go

go:
  - 1.16.x

services:
  - docker

env:
  global:
    - GO111MODULE=on
    - GOTFLAGS="-race"
    - IPFS_PATH=/tmp/ipfs
  matrix:
    - BUILD_DEPTYPE=gomod

before_install:
  - (cd /tmp && go install github.com/ipfs/go-ipfs/cmd/ipfs@fd6676f4afe43324629ab1a618ba1169fe2c3c2a)
  - mkdir /tmp/ipfs && chmod 0777 /tmp/ipfs
  - ipfs init
  - (ipfs daemon --enable-namesys-pubsub &)
install:
  - go mod download

before_script:
  - go vet ./...

script:
  - go get -d github.com/cheekybits/is/... # remove with gx
  - bash <(curl -s https://raw.githubusercontent.com/ipfs/ci-helpers/master/travis-ci/run-standard-tests.sh)


cache:
  directories:
    - $GOPATH/src/gx
    - $GOPATH/pkg/mod
    - $HOME/.cache/go-build

notifications:
  email: false
